In [45]:
print(sklearn.__version__)

0.22.1


In [2]:
import sklearn
import numpy as np
import pandas as pd

In [3]:
sklearn.__version__

'0.22.1'

In [4]:
from sklearn.model_selection import train_test_split
#to split train and test data

In [5]:
from sklearn import preprocessing
from sklearn.ensemble import RandomForestRegressor 
#preprocessing and random forest model 

In [7]:
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV
#cross-validation pipeline

In [42]:
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error
#evaliation metrics

In [10]:
from sklearn.externals import joblib
#module to save scikit learn models

In [11]:
#loading the red wine dataset(csv)
dataset="D:\Kaggle-titanic\datasets_4458_8204_winequality-red.csv"

In [12]:
data=pd.read_csv(dataset)

In [13]:
data.head(10)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   
5            7.4              0.66         0.00             1.8      0.075   
6            7.9              0.60         0.06             1.6      0.069   
7            7.3              0.65         0.00             1.2      0.065   
8            7.8              0.58         0.02             2.0      0.073   
9            7.5              0.50         0.36             6.1      0.071   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   
5                 13.0                  40.0   0.9978  3.51       0.56   
6                 15.0                  59.0   0.9964  3.30       0.46   
7                 15.0                  21.0   0.9946  3.39       0.47   
8                  9.0                  18.0   0.9968  3.36       0.57   
9                 17.0                 102.0   0.9978  3.35       0.80   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5  
5      9.4        5  
6      9.4        5  
7     10.0        7  
8      9.5        7  
9     10.5        5

In [14]:
print data.shape

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(data.shape)? (<ipython-input-14-b63b528871a5>, line 1)

In [15]:
data.shape

(1599, 12)

In [16]:
y=data.quality
X=data.drop('quality',axis=1)
#seperating target from the feature set

In [17]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=123,stratify=y)

In [18]:
scaler=preprocessing.StandardScaler().fit(X_train)

In [19]:
X_train_scaled=scaler.transform(X_train)
#scaling to get the mean around 0 and std around 1.

In [22]:
X_train_scaled.mean(axis=0)
#confirming

array([ 1.16664562e-16, -3.05550043e-17, -8.47206937e-17, -2.22218213e-17,
        1.94440936e-17, -6.38877362e-17, -4.16659149e-18, -1.20753377e-13,
       -8.70817622e-16, -4.08325966e-16, -1.17220107e-15])

In [21]:
X_train_scaled.std(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
X_test_scaled=scaler.transform(X_test)
#applying transformer on the test data

In [26]:
X_test_scaled.mean(axis=0)


array([ 0.02776704,  0.02592492, -0.03078587, -0.03137977, -0.00471876,
       -0.04413827, -0.02414174, -0.00293273, -0.00467444, -0.10894663,
        0.01043391])

In [27]:
X_test_scaled.std(axis=0)

array([1.02160495, 1.00135689, 0.97456598, 0.91099054, 0.86716698,
       0.94193125, 1.03673213, 1.03145119, 0.95734849, 0.83829505,
       1.0286218 ])

In [28]:
pipeline=make_pipeline(preprocessing.StandardScaler(),RandomForestRegressor(n_estimators=100))

In [30]:
pipeline.get_params()

{'memory': None,
 'steps': [('standardscaler',
   StandardScaler(copy=True, with_mean=True, with_std=True)),
  ('randomforestregressor',
   RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                         max_depth=None, max_features='auto', max_leaf_nodes=None,
                         max_samples=None, min_impurity_decrease=0.0,
                         min_impurity_split=None, min_samples_leaf=1,
                         min_samples_split=2, min_weight_fraction_leaf=0.0,
                         n_estimators=100, n_jobs=None, oob_score=False,
                         random_state=None, verbose=0, warm_start=False))],
 'verbose': False,
 'standardscaler': StandardScaler(copy=True, with_mean=True, with_std=True),
 'randomforestregressor': RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       max_samples=None, min_impurity_decrease=0.0,
 

In [31]:
hyperparameters={'randomforestregressor__max_features':['auto','sqrt','log2'],'randomforestregressor__max_depth':[None,5,3,1]}
#initialising the hyperparameters

In [33]:
clf=GridSearchCV(pipeline,hyperparameters,cv=10)
#cross validation using k folds

In [34]:
clf.fit(X_train,y_train)
#fitiing on the training set

GridSearchCV(cv=10, error_score=nan,
             estimator=Pipeline(memory=None,
                                steps=[('standardscaler',
                                        StandardScaler(copy=True,
                                                       with_mean=True,
                                                       with_std=True)),
                                       ('randomforestregressor',
                                        RandomForestRegressor(bootstrap=True,
                                                              ccp_alpha=0.0,
                                                              criterion='mse',
                                                              max_depth=None,
                                                              max_features='auto',
                                                              max_leaf_nodes=None,
                                                              max_samples=None,
                            

In [36]:
clf.best_params_

{'randomforestregressor__max_depth': None,
 'randomforestregressor__max_features': 'log2'}

In [38]:
clf.refit
#the model will be retrained for better performance

True

In [50]:
y_pred=clf.predict(X_test)
#predicting the data on test set
y_pred

array([6.37, 5.69, 4.94, 5.47, 6.22, 5.6 , 5.09, 4.85, 5.03, 6.11, 5.37,
       5.76, 5.85, 5.14, 5.71, 5.73, 6.62, 5.7 , 5.71, 6.99, 5.46, 5.74,
       5.04, 6.03, 6.03, 5.03, 5.37, 5.16, 6.03, 6.  , 5.9 , 6.62, 6.  ,
       5.02, 4.98, 5.99, 5.08, 6.14, 5.06, 6.16, 4.93, 5.8 , 6.67, 5.07,
       6.18, 5.31, 5.42, 5.62, 5.08, 6.43, 6.19, 5.38, 5.84, 5.18, 5.64,
       5.8 , 5.32, 5.31, 4.99, 5.27, 5.24, 5.15, 5.07, 5.8 , 6.05, 5.29,
       6.49, 5.02, 5.2 , 6.63, 5.83, 5.71, 5.16, 5.03, 5.43, 5.99, 5.24,
       5.08, 5.18, 5.3 , 6.25, 5.6 , 6.15, 6.31, 5.07, 5.93, 6.52, 6.41,
       5.82, 5.83, 5.95, 5.37, 6.33, 5.66, 5.66, 5.81, 6.77, 6.73, 5.62,
       6.77, 5.13, 5.35, 5.11, 6.39, 5.04, 4.75, 5.62, 4.97, 5.58, 6.04,
       5.93, 5.7 , 6.06, 5.34, 5.2 , 5.18, 5.97, 5.06, 4.85, 5.92, 5.92,
       5.08, 5.7 , 6.2 , 5.3 , 5.29, 5.3 , 5.95, 5.5 , 5.24, 5.83, 6.29,
       5.19, 5.33, 5.02, 6.31, 4.99, 5.2 , 6.69, 5.47, 5.21, 5.05, 5.51,
       6.06, 5.31, 5.48, 5.13, 6.62, 5.93, 5.1 , 5.

In [40]:
mean_squared_error(y_test,y_pred)
#calculating accuracy

0.340224375

In [43]:
mean_absolute_error(y_test,y_pred)
#calculating accuracy

0.41612499999999997

In [46]:
r2_score(y_test,y_pred)
#calculating accuracy

0.472743870694352

In [47]:
joblib.dump(clf,'random_forest_regressor.pkl')
#save model to .pkl file

['random_forest_regressor.pkl']

In [48]:
# clf2=joblib.load('random_forest_regressor.pkl')
#to load the model again for future use

In [49]:
# clf2.predict(X_test)

array([6.37, 5.69, 4.94, 5.47, 6.22, 5.6 , 5.09, 4.85, 5.03, 6.11, 5.37,
       5.76, 5.85, 5.14, 5.71, 5.73, 6.62, 5.7 , 5.71, 6.99, 5.46, 5.74,
       5.04, 6.03, 6.03, 5.03, 5.37, 5.16, 6.03, 6.  , 5.9 , 6.62, 6.  ,
       5.02, 4.98, 5.99, 5.08, 6.14, 5.06, 6.16, 4.93, 5.8 , 6.67, 5.07,
       6.18, 5.31, 5.42, 5.62, 5.08, 6.43, 6.19, 5.38, 5.84, 5.18, 5.64,
       5.8 , 5.32, 5.31, 4.99, 5.27, 5.24, 5.15, 5.07, 5.8 , 6.05, 5.29,
       6.49, 5.02, 5.2 , 6.63, 5.83, 5.71, 5.16, 5.03, 5.43, 5.99, 5.24,
       5.08, 5.18, 5.3 , 6.25, 5.6 , 6.15, 6.31, 5.07, 5.93, 6.52, 6.41,
       5.82, 5.83, 5.95, 5.37, 6.33, 5.66, 5.66, 5.81, 6.77, 6.73, 5.62,
       6.77, 5.13, 5.35, 5.11, 6.39, 5.04, 4.75, 5.62, 4.97, 5.58, 6.04,
       5.93, 5.7 , 6.06, 5.34, 5.2 , 5.18, 5.97, 5.06, 4.85, 5.92, 5.92,
       5.08, 5.7 , 6.2 , 5.3 , 5.29, 5.3 , 5.95, 5.5 , 5.24, 5.83, 6.29,
       5.19, 5.33, 5.02, 6.31, 4.99, 5.2 , 6.69, 5.47, 5.21, 5.05, 5.51,
       6.06, 5.31, 5.48, 5.13, 6.62, 5.93, 5.1 , 5.